# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  #virtutalmachine resources
  config.vm.provision "shell", inline: <<-SHELL
    #.net core rutime install
    sudo apt-get update &&\
    sudo apt-get install curl -y &&\
    sudo apt install apt-transport-https ca-certificates curl software-properties-common -y && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" &&\
    sudo apt-get update && \
    sudo apt-cache policy docker-ce && \
    sudo apt install docker-ce -y && \
    sudo docker pull
    sudo docker run --name ubuntu -p 80:80 ubuntu   
    sudo apt-get install openjdk-11-jdk -y && \
    sudo apt-get install maven -y && \
    sudo apt-get install git -y && \
    git clone https://github.com/prof-emilio-resende/java-imc-calc-api.git && \
    'cd' java-imc-calc-api && \
    mvn install && \
    mvn spring-boot:run

  SHELL
end
 
