# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  #box image
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  
  #porta
  config.vm.network  "forwarded_port", guest: 3306, host: 3306 

  #vm name
    config.vm.define "mysql" do |mysql|
  end

  #hostname
  config.vm.hostname = "mysql" 

  #virtutalmachine resources
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install mysql-server
    systemctl status mysql
    apt-get install -y openjdk-8-jdk
    apt-get install -y curl vim
    cd /home
    mmkdir /home/ramonfreitas
  SHELL

end
