# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  #box image
  config.vm.box = "ncaro/php7-debian8-apache-nginx-mysql"
  
  #porta
  config.vm.network  "forwarded_port", guest: 80, host: 3306 

  #ip
  config.vm.network  "private_network", ip: "192.168.55.20"

  #pasta
  config.vm.synced_folder "./", "/nintendodata"

  #vm name
    config.vm.define "mysql" do |mysql|
  end

  #hostname
  config.vm.hostname = "mysql" 

  #virtutalmachine resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  #virtutalmachine resources
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y openjdk-8-jdk
    apt-get install -y curl vim
    cd /home
    mmkdir /home/ramonfreitas
  SHELL

end
