# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config| 
  config.vm.box = "ubuntu/bionic64"

    config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update &&\
    wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb &&\
    sudo dpkg -i packages-microsoft-prod.deb &&\
    sudo apt-get update &&\
    sudo apt-get install -y apt-transport-https &&\
    sudo apt-get update &&\
    sudo apt-get install -y dotnet-sdk-5.0 &&\
    sudo apt-get install -y apt-transport-https &&\
    sudo apt-get update &&\
    sudo apt-get install -y aspnetcore-runtime-5.0
   SHELL
end
